### ISSUE TITLE
Syslog Configuration not present and intersight status

### ISSUE THREAD

**Issue by bakrir** [vesposito/easyucs#11]
Hi, great work on this tool! I have been testing it and thinking of several ways this can be used.

I had a couple of items that I wanted to bring up:

1. I was going through the configuration file and I noticed syslog configuration was not present. Could this be added?

2. I also noticed the `intersight_status` was not accurate for some sites (all running the same code). Some status for claimed devices showed as `unclaimed` or `unknown` but they were claimed. Could you also show the `access-mode` (Read-only, Allow Control)?

**Comment by vesposito** [comment]
Hello, thanks for the feedback!

1. When you say that the syslog configuration is not present, which version of EasyUCS are you running? For which kind of device is this (IMC, UCSM or UCS Central)?
2. For what kind of device is this (IMC, UCSM)? Currently EasyUCS only fetches the Intersight claim status information from the UCS XML API, but I think I know how to enhance this in the future to gather extra details, like access mode and Intersight Account Name.

**Comment by bakrir** [comment]
Hi, I should have been clearer on the endpoint (sorry about that). These are all against UCSM and I realized that my EasyUCS version was not up to date so I testing using 0.9.7 which mentions syslog was added 🤦🏻‍♂️. One suggestion, it would be helpful to add a `-v` and  `--version` to the cli tool. 

1. After updating my EasyUCS repo I run the `config fetch` again and I now see the syslog configuration. 👍

2. I am testing this against the moment. We are starting to add IMCs to intersight being able to report on that would be handy :-).

The config file still shows intersight_status as `unknown` any idea on why that might be? in UCSM it is showing as claimed.

Thank you for the quick response and help.

**Comment by vesposito** [comment]
Hello,
I've just uploaded version 0.9.7.1 which now displays EasyUCS version at launch. I'll try to add a `-v` option in the next release.
Regarding the `intersight_status` value, EasyUCS will now display a warning message in case it was not able to get the required object from the UCSM API. It currently uses XML API object "cloudDeviceConnectorEp", but it is unfortunately not available in UCSM 3.2 - this might be why it appears as `unknown` in your environment.

**Comment by bakrir** [comment]
The ucsm domains that I am running it against are on 4.x. and I just tested it on a POD that I recenetly added to intersight and still getting `unknown` on that as well.

**Comment by vesposito** [comment]
Hello,
I have just pushed a new release (0.9.7.2) which is now able to fetch the Intersight Device Connector information in the inventory & config of the UCSM / IMC device. It also contains additional details of the Device Connector, and is even able to perform some config operations with it.
Let me know if it works better for you!
