### ISSUE TITLE
Validation of "vlan" name in lan connectivity policy is too short.

### ISSUE THREAD

**Issue by pvarga** [vesposito/easyucs#13]
If a "vlan" has a name longer than 16 characters and is referenced within a lan connectivity policy, the validation will throw an error because the lan connectivity policy is expecting a vlan name no longer than 16 characters.  I'll be submitting a PR to adjust the length to match the validation of the underlying vlan object.

**Comment by vesposito** [comment]
Good catch. This is only for iSCSI vNICs though, for regular vNICs the validation is fine.

Your fix looks good to me, I'll merge it.
