### ISSUE TITLE
Typo in device -h help

### ISSUE THREAD

**Issue by lengoldenstein** [vesposito/easyucs#19]
Small typo in the description of 'device -h' I noticed:
    clear_user_sessions
                        Clears all user sessions of an UCS device
    clear_intersight_claim_status
                        Clears all user sessions of an UCS device

easyucs$ python3 easyucs.py device -h

EasyUCS 0.9.7.4 created by Marc Abu El Ghait, Franck Bonneau and Vincent Esposito, Copyright 2016-2021, Cisco

usage: easyucs.py device [-h]
                         {regenerate_certificate,clear_sel_logs,clear_user_sessions,clear_intersight_claim_status}
                         ...

optional arguments:
  -h, --help            show this help message and exit

Action:
  {regenerate_certificate,clear_sel_logs,clear_user_sessions,clear_intersight_claim_status}
                        Device actions
    regenerate_certificate
                        Regenerate self-signed certificate of an UCS system
    clear_sel_logs      Clears all SEL logs of an UCS device
    clear_user_sessions
                        Clears all user sessions of an UCS device
    clear_intersight_claim_status
                        Clears all user sessions of an UCS device

Examples:
      python easyucs.py device regenerate_certificate -t ucsm -i 192.168.0.1 -u admin -p password
            regenerate self-signed certificate of UCS system

      python easyucs.py device clear_sel_logs -t ucsm -i 192.168.0.1 -u admin -p password
            clear SEL Logs of all discovered servers of UCS system

**Comment by vesposito** [comment]
Thanks for the catch! I have fixed this internally and it will be pushed with the next update.

**Comment by vesposito** [comment]
Fixed in v0.9.8.5
