### ISSUE TITLE
support python 3.9

### ISSUE THREAD

**Issue by DisasteR** [vesposito/easyucs#20]
xml.etree.ElementTree.Element.getchildren is Deprecated since version 3.2, and removed in version 3.9: Use list(elem) or iteration.

**Comment by vesposito** [comment]
This is dependent on ucsmsdk support for Python 3.9. There is a pull request opened for this here: https://github.com/CiscoUcs/ucsmsdk/issues/204

**Comment by vesposito** [comment]
For your information, ucsmsdk 0.9.12 has just been released and includes fixes for this issue to support Python 3.9

**Comment by pattiking** [comment]
@vesposito is there a planned release date for the support of python 3.9 ?

**Comment by vesposito** [comment]
Hi @pattiking, I haven't tested it, but I guess if you simply update ucsmsdk to the latest version it might work fine...

**Comment by pattiking** [comment]
unfortunately not for us, we have been using it together with Pyhton 3.8.10 (32bit) and needed to upgrade python to 3.9. we tested both versions 32bit and 64 bit but with both of them the tool isn't working anymore

**Comment by vesposito** [comment]
Can you please share some details about the issue you're facing? Some logs/error messages?

**Comment by pattiking** [comment]
hi, I would need to rebuilt the non-working config first. but after we upgraded python to the latest 3.9 release we couldn't update the modules anymore as there was an error with them being incompatible.

**Comment by pattiking** [comment]
do you have a running instance of easyucs on python 3.9 ? if yes, could you do a "pip freeze" or "python -m pip freeze" for me and share the output ? maybe I'm missing a required package.

**Comment by vesposito** [comment]
All 3 UCS SDKs have been updated to support Python 3.9. Closing this.
