### ISSUE TITLE
Cant ope the GUI on Mac

### ISSUE THREAD

**Issue by tjanitsc** [vesposito/easyucs#25]
I'm have all the requirements. But cant open the GUI.

Error:

python3 /Users/tjanitsc/easyucs/easyucs_gui.py
Traceback (most recent call last):
  File "/Users/tjanitsc/easyucs/easyucs_gui.py", line 10, in <module>
    from flask import Flask, request, abort, jsonify
ModuleNotFoundError: No module named 'flask'
<img width="894" alt="Screenshot 2023-03-01 at 10 53 38" src="https://user-images.githubusercontent.com/37362339/222105602-87890c60-7779-4da7-a4e4-bcd790f2238c.png">

**Comment by mabuelgh** [comment]
What is the version of Python3 and version of Flask that you have in your setup?

**Comment by tjanitsc** [comment]
python3
Python 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin

**Comment by tjanitsc** [comment]
flask --version
Python 3.9.12
Flask 2.2.3
Werkzeug 2.2.3

**Comment by mabuelgh** [comment]
Can you try to go on a virtual environnement and make sure to install all the required python modules associated with the python version that you are using

**Comment by tjanitsc** [comment]
how can I create a report (doc) from a standalone server? which cli string can I use?

**Comment by tjanitsc** [comment]
on a windows machine the gui is also not working..

**Comment by mabuelgh** [comment]
According to your first logs it seems that the module flask is not installed/linked with the Python version you're using. 
Please make sure that you are using the same python version for the execution of the code and for the installation of the required modules.


The CLI command to generate a report is on the readme, change the type from "ucsm" to "cimc"  : 
python easyucs.py report generate -t cimc -i 192.168.0.1 -u admin -p password -o output/reports

**Comment by tjanitsc** [comment]
dont know how to use this with a "virtualized environment", also get errors with the cli command

**Comment by tjanitsc** [comment]
thanks for your help but i think 1. the documentation isnt sufficient or 2nd it dont work anymore. With this circumstances it costs to much time it bring to work...

**Comment by mabuelgh** [comment]
I just tried it with version 3.10.9 as 3.11 should not be working because of a deprecated feature. 
My commands : 

`pyenv shell 3.10.9` 
`pip install -r requirements.txt`
`python easyucs.py report generate -t cimc -i 192.168.1.10 -u admin -p password -o output/reports`

And it worked just fine!

**Comment by tjanitsc** [comment]
Thanks! Tim

From: Marc Abu El Ghait ***@***.***>
Date: Thursday, 2. March 2023 at 09:48
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

I just tried it with version 3.10.9 as 3.11 should not be working because of a deprecated feature.
My commands :

pyenv shell 3.10.9
pip install -r requirements.txt
python easyucs.py report generate -t cimc -I 192.168.1.10 -u admin -p password -o output/reports

And it worked just fine!

**Comment by tjanitsc** [comment]
Hi, I uninstalled python3.11 and install python 3.10.9

But get error like this:

easyucs tjanitsc$ python3 easyucs.py report generate -t cimc -I 10.30.136.51 -u admin -p password -o output/reports

Traceback (most recent call last):

  File "/Users/tjanitsc/easyucs/easyucs.py", line 12, in <module>

    from imcsdk.imchandle import ImcHandle

ModuleNotFoundError: No module named 'imcsdk'

Before this, I intalled the module:
Pip install imcsdk

Regards, Tim

From: Tim Janitschke (tjanitsc) ***@***.***>
Date: Thursday, 2. March 2023 at 14:07
To: vesposito/easyucs ***@***.***>, vesposito/easyucs ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)
Thanks! Tim

From: Marc Abu El Ghait ***@***.***>
Date: Thursday, 2. March 2023 at 09:48
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

I just tried it with version 3.10.9 as 3.11 should not be working because of a deprecated feature.
My commands :

pyenv shell 3.10.9
pip install -r requirements.txt
python easyucs.py report generate -t cimc -I 192.168.1.10 -u admin -p password -o output/reports

And it worked just fine!

**Comment by mabuelgh** [comment]
Hi,

Can you try to install all the required modules with the following:

`python3 -m pip install -r requirements.txt`

And check again if you can create your report now

**Comment by tjanitsc** [comment]
TJANITSC-M-66SF:easyucs tjanitsc$ python3 -m pip -r requirements.txt



Usage:

  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip <command> [options]



no such option: -r


From: Marc Abu El Ghait ***@***.***>
Date: Friday, 3. March 2023 at 12:16
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

Hi,

Can you try to install all the required modules with the following:

python3 -m pip -r requirements.txt

And check again if you can create your report now

**Comment by mabuelgh** [comment]
I forgot the "install", this one : 

`python3 -m pip install -r requirements.txt`

**Comment by tjanitsc** [comment]
python3 easyucs.py report generate -t cimc -I 10.30.136.51 -u admin -p password -o output/reports



EasyUCS 0.9.7.6 created by Marc Abu El Ghait, Franck Bonneau and Vincent Esposito, Copyright 2016-2022, Cisco



usage: easyucs.py report generate [-h] -i IP -u USERNAME -p PASSWORD

                                  [-t {ucsm,cimc}] [-s {a4,letter}] [-v]

                                  [-l LOGFILE] -o OUTPUT_DIRECTORY [-y]

easyucs.py report generate: error: the following arguments are required: -i/--ip


From: Marc Abu El Ghait ***@***.***>
Date: Friday, 3. March 2023 at 12:20
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

I forgot the "install", this one :

python3 -m pip install -r requirements.txt

**Comment by tjanitsc** [comment]
Ok I have to use the small i..

From: Marc Abu El Ghait ***@***.***>
Date: Friday, 3. March 2023 at 12:20
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

I forgot the "install", this one :

python3 -m pip install -r requirements.txt

**Comment by tjanitsc** [comment]
Hi,

is this a report as expected(attached)? Hmm, I miss the VIC configuration with vnics..

Regards, Tim

From: Marc Abu El Ghait ***@***.***>
Date: Friday, 3. March 2023 at 12:20
To: vesposito/easyucs ***@***.***>
Cc: Tim Janitschke (tjanitsc) ***@***.***>, Author ***@***.***>
Subject: Re: [vesposito/easyucs] Cant ope the GUI on Mac (Issue #25)

I forgot the "install", this one :

python3 -m pip install -r requirements.txt

**Comment by mabuelgh** [comment]
I don't see any attached files due to the "email answer"

The VNICs are not present on the CIMC report but can be viewed on the config JSON file that has also been generated in the process

**Comment by vesposito** [comment]
Please have a look at the new GUI available in v0.9.8.5.
Closing this as it was an issue with requirements not being properly installed
