### ISSUE TITLE
Missing catalog files for UCSB-200-M6

### ISSUE THREAD

**Issue by Hin-M** [vesposito/easyucs#26]
Since the last time the catalog was updated Cisco has released a new version of the UCSB 200 blade which is already in use has come out, but the repository is missing the UCSB-200-M6.json file to properly identify and inventory the blade.

Right now I am attempting to use a modified M5 definition, but official support for the blade would obviously be preferred

**Comment by vesposito** [comment]
I have a long overdue update to do on EasyUCS, which would contain all M6 servers compatibility, and much much more. Will try to prioritise this in the coming weeks.

**Comment by vesposito** [comment]
Fixed in v0.9.8.5
