### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by markshannon1974** [vesposito/easyucs#8]
hi

great code :)  the report is excellent.

pretty new to json files etc.  quick question pls...if i edit the exported json file with only a small piece of config left will it just apply that and not wipe anything else?

thanks

**Comment by vesposito** [comment]
Hello,
Thanks for the feedback :) Happy that this is useful to you.

When pushing a config, EasyUCS is not fetching the current config and doing a diff, it's simply pushing what you're giving as input in the JSON file. 
If you edit the exported JSON file with a small piece of config and push it, it will reapply every single line of config that is in your JSON file, with some things that might be disruptive.

The best thing to do would be to remove everything that you don't need, and only have the new portion of the config that you would like to push to the system. This way, only that part will get pushed, and you have no risk of being disruptive to other parts of the configuration.

Hope this makes it more clear :)

Cheers.

**Comment by markshannon1974** [comment]
Hi
yes thats great.
does it pull all the default policies etc? or service profiles?
ideally going to use this config file to apply to new deployments.
thanks

**Comment by vesposito** [comment]
Hello,

For now yes, EasyUCS pulls all default policies, templates and service profiles that are configured in a UCS domain. But you can easily edit the JSON file after fetching a config from a live system to remove what you don't need, before pushing it to a new domain.

In the samples/ directory, you will also find some examples of configs, some of which only contain a small portion of configuration.

Hope this helps!

**Comment by markshannon1974** [comment]
Brilliant thanks
