### ISSUE TITLE
Sorry, on my site the tool is doing nothing.

### ISSUE THREAD

**Issue by tjanitsc** [vesposito/easyucs#9]
![image](https://user-images.githubusercontent.com/37362339/82560995-d330f700-9b72-11ea-8b01-736469c6d67b.png)

**Comment by tjanitsc** [comment]
seems it stuck in the starting procedure

**Comment by tjanitsc** [comment]
ok, now Im understand, i have to brows to 127.0.0.1...

**Comment by vesposito** [comment]
If you want to use the GUI, yes, you have to browse to http://127.0.0.1:5000/
GUI will let you push configuration to a live UCS device (UCSM, CIMC or Central).

If you want to generate documentation, or fetch a config/inventory, you will have to use the CLI. Look at the "[Getting Started](https://github.com/vesposito/easyucs#getting-started)" section for how to use the CLI.
